# Generated by Django 5.0.3 on 2024-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('tons', 'Tons'), ('bags', 'Bags')], max_length=4)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(max_length=45)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('invoice_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
