# Generated by Django 5.0.3 on 2024-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='product_id',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
