# Generated by Django 5.0.3 on 2024-07-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytical_dashboard.customer'),
        ),
    ]
