# Generated by Django 5.0.3 on 2024-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0003_expensecategory_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='expenser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
