# Generated by Django 5.0.3 on 2024-08-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0004_remove_expense_transaction_id_expense_expense_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit card', 'Credit Card'), ('Cheque', 'Cheque')], max_length=20),
        ),
    ]
