# Generated by Django 5.0.3 on 2024-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0005_alter_sales_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('BAGS', 'Bags'), ('TONS', 'Tons')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
