# Generated by Django 5.0.3 on 2024-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0007_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receivable', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
