# Generated by Django 5.0.3 on 2024-08-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0008_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='payable',
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
