# Generated by Django 5.0.3 on 2024-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0010_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='units',
            field=models.CharField(choices=[('bags', 'Bags'), ('tons', 'Tons')], default='bags', max_length=50),
        ),
    ]
