# Generated by Django 5.0.3 on 2024-08-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0011_purchase_payable_purchase_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='receivable',
        ),
    ]
