# Generated by Django 5.0.3 on 2024-08-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0012_remove_supplier_receivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
