# Generated by Django 5.0.3 on 2024-08-12 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0013_customer_payable_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online Transfer'), ('cheque', 'Cheque Payable')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='analytical_dashboard.customer')),
            ],
        ),
    ]
