# Generated by Django 5.0.3 on 2024-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0014_advancedeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
