# Generated by Django 5.0.3 on 2024-08-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0015_alter_sales_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
