# Generated by Django 5.0.3 on 2024-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0016_alter_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
