# Generated by Django 5.0.3 on 2024-09-07 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical_dashboard', '0017_alter_customer_credit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='units',
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_brand', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('units', models.CharField(choices=[('bags', 'Bags'), ('tons', 'Tons')], default='bags', max_length=50)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='analytical_dashboard.purchase')),
            ],
        ),
    ]
